<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Server/AGUIWebChat.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="xunit.runner.visualstudio" Version="4.0.1" />
    <PackageReference Update="xunit.v3" Version="4.0.2" />
  </ItemGroup>
</Project>
