// <auto-generated />
using AGUIWebChat.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGUIWebChat.Server.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260921210607_SeedOllamaProvider")]
    partial class SeedOllamaProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("bit");

                    b.Property<string>("ThinkingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ModelId")
                        .IsUnique();

                    b.ToTable("AIModels", (string)null);
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModelDefaults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AIModelId")
                        .HasColumnType("int");

                    b.Property<int?>("NumCtx")
                        .HasColumnType("int");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<int?>("TopK")
                        .HasColumnType("int");

                    b.Property<double?>("TopP")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AIModelId")
                        .IsUnique();

                    b.ToTable("AIModelDefaults", (string)null);
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModelReasoningEffort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AIModelId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AIModelId", "Value")
                        .IsUnique();

                    b.ToTable("AIModelReasoningEfforts", (string)null);
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AIProviders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            Name = "Ollama",
                            ProviderType = "Ollama"
                        });
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModel", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Domain.AI.AIProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModelDefaults", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Domain.AI.AIModel", "AIModel")
                        .WithOne("Defaults")
                        .HasForeignKey("AGUIWebChat.Server.Domain.AI.AIModelDefaults", "AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModelReasoningEffort", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Domain.AI.AIModel", "AIModel")
                        .WithMany("ReasoningEfforts")
                        .HasForeignKey("AIModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIModel", b =>
                {
                    b.Navigation("Defaults");

                    b.Navigation("ReasoningEfforts");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Domain.AI.AIProvider", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
